name: Raaghu Docs Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment:
      name: "Production"
    name: Build and Deploy Job
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GROUND_01D63070F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"
          skip_api_build: "true"
